### PR TITLE
Add support for int64 values

### PR DESCRIPTION
**Pull request by egasimus**
:)

### CODE REVIEW

**Comment by colinbdclark** [comment]
This is awesome, thanks so much, @egasimus! I'll review this pull and merge it soon.

**Comment by egasimus** [comment]
Hey, get a load of this: if there's a checkout of Long.js under `./node_modules/long` and another in `./node_modules/osc/node_modules/long`, and I pass an instance of the former to `inferTypeForArgument`, the `instanceof` check therein fails, throwing the `Can't infer` error. Even if the two checkouts are the same version, Node doesn't see them as the same thing -- just unfortunate namesakes which exist in separate modules and are, therefore, very much separate. Certainly not what one would expect to happen.

It's been easy enough to hack around this by using `require('osc/node_modules/long')` in place of `require('long')` in my project -- but that's just stupid :/ Furthermore, for an instance of `Long`, `arg.constructor.name` is an empty string because Long.js does `var Long = function(...)` rather than `function Long` or any variety thereof. Short of sending in a pull request to fix the constructor name (which I'll probably do anyway at some point) -- and given your expressed dissatisfaction with the `inferTypeForArgument` code -- do you have any ideas about how to identify `Long`s?

Perhaps we should duck type the whole thing? `arg.high instanceof Number && arg.low instanceof Number`, possibly `&& arg.unsigned === false`, and be done with it?

**Comment by colinbdclark** [comment]
Hey, thanks for finding this. I can think of two scenarios to consider:

1. Ideally, we'd refactor <code>inferTypeForArgument</code> so that there are pluggable strategies, not unlike what we've got for reading and writing types. So we'd expand the <code>argumentTypes</code> structs for each type, specifying a "typeInferrer" function for each.

2. The simpler, though less pristine, technique is to just extend the conditional inside the <code>object</code> case to duck type check for Long instances.

Given the amount of work in the former, I'd suggest going ahead with the latter, and we can file a bug about improving the type inference strategy in the future.

What do you think?

**Comment by egasimus** [comment]
I'd go with the duck typing. Considering the current architecture I don't see much of a case for pluggable inference strategies, at least for the time being.

**Pull request merged**
