### PR TITLE
encode utf8 strings if Buffer or TextEncoder is available

### PR DESCRIPTION
**Pull request by jean-emmanuel**
This PR adds utf8 strings encoding, the same way utf8 strings are currently decoded.

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
I've pushed a second commit that prevents creating a new TextDecoder/TextEncoder instance every time a string is read/written.

**Comment by jean-emmanuel** [comment]
@colinbdclark Have you had a chance to look at this ?

**Comment by colinbdclark** [comment]
Hi @jean-emmanuel, thanks for this fix. I've published it as v2.4.0. Apologies for the long wait to merge this. It's been maybe the busiest two months of my life!

**Comment by jean-emmanuel** [comment]
Thanks a lot for reviewing / merging, and no problem, real life is good too :)

**Pull request merged**
