### PR TITLE
add grunt replace task to fix relative path in concat task

### PR DESCRIPTION
**Pull request by knoblochtobias**
Some output files in the dist folder containing a relative require with a wrong path. This leads to an error, if you require them.

I'm not sure if this is the best solution, but it's working.

### CODE REVIEW

**Comment by colinbdclark** [comment]
Hi @knoblochtobias, thanks for the pull request. Sorry to hear you're having difficulties using osc.js.

This fix seems a bit strange to me. Can you tell me more about how you're using osc.js, and the problem you're encountering? Which environment (browser, Node.js, etc.) are you using? Are you using additional build tooling of some kind?

The files in the <code>dist<code> directory are generally for use in a browser-like environment. They're intended to work as-is and are fully self-contained, so those require statements, which are all guarded, will never evaluate. If you're using osc.js in Node.js or the main process of an Electron application, you should require the module directly, rather than using any of the concatenated files. Similarly, if you're using some kind of build-time tooling to process osc.js' source files in any way, you should not use the files in <code>dist</code>.

If you can share a bit more background information about your issue, I'll see what I can to help sort it out, but I don't think rewriting URLs in pre-compiled files will be necessary unless something subtle is happening here that no one else has encountered before.

**Comment by knoblochtobias** [comment]
Hi @colinbdclark,
thanks for your help :)

I tried to bump the osc version in the following tuio.js library:
https://github.com/nomve/Tuio.js/pull/5

Here the travis ci, where the problems happened:
https://travis-ci.org/nomve/Tuio.js/builds/368545806

**Comment by nomve** [comment]
I don't really have an opinion on this PR, but a couple of points:

1) you are already exporting the osc module for commonjs environments here https://github.com/colinbdclark/osc.js/blob/master/dist/osc-browser.js#L1064-L1066 so to me it's valid to require it. In general, any bundler will fail with this because it will not be able to resolve `../osc` since it doesn't exist

2) https://github.com/colinbdclark/osc.js/blob/master/dist/osc-browser.js#L1997
`osc.WebSocket = typeof WebSocket !== "undefined" ? WebSocket : require ("ws");`
browserify or any bundler can't really know if `WebSocket` exists at build time so it's always forced to include `ws` in the final bundle which it probably should not do

3) also as mentioned in the other PR, changing to `require('osc')` makes browserify work, but only because `osc` is not included in the bundle. If it was, then importing `dgram` etc. would not work

**Comment by nomve** [comment]
but btw, many thanks for creating this. It worked really well when I needed it.

**Comment by colinbdclark** [comment]
Thanks for your comments, @nomve. First, a quick summary of what the files in osc.js' <code>dist/</code> directory are for:

- <code>osc-browser.js</code> is an all-in-one file that contains osc.js as well as all of its dependencies. It is, as you note, wrapped in UMD-style boilerplate to support its use within module loaders such as Require.js. It is intended to be a universal file that can be used anywhere, including with a plain old script tag.
- <code>osc-module.js</code> contains only osc.js' web platform code, also wrapped in UMD boilerplate. It does not include any of osc.js' dependencies, and expects you will load these via whatever mechanism you prefer ([as you can see in this unit test](https://github.com/colinbdclark/osc.js/blob/master/tests/osc-module-tests.js#L15-L22)).

I think either file should work for you, depending on how you want to manage transitive dependencies.

In response to your other questions:

1. As you saw with your recent commits to Tuio.js, it's perfectly valid to <code>require</code> one of osc.js' built files. It's not, however, apparently viable to run either of these files (which have already been processed and bundled) through your toolchain. There must be some way to tell Browserify to leave certain files alone, no?

2. There's a little irony here—an entire toolchain designed to make code more portable between Node.js and the browser environment, which is unable to handle a simple dynamic loading situation that serves exactly this purpose. Even my linter knows that the WebSocket global is available in a browser! Nonetheless, my goal with osc.js has always been to make it as universal to and agnostic of people's various preferences for toolchains and build environments as possible. So, now that I understand how Browserify works, I think I have a sense of how it, too, can be accommodated. But it looks like it will require further modularization (I'm planning to split up osc.js into multiple modules using a monorepo), since I'll have to create a kind of "node-style web module" that jives with Browserify's preprocessor's static view of the world. As I'm sure you know, it's tough when this is a spare time thing, but I'll try to prioritize it.

3. Yup, that makes sense.

I really appreciate you taking the time to explain some of this, and to troubleshooting and triaging this issue. Sorry that you had to implement such a hack on your end to make it work. :(

On my end, I'll need to think through whether the workaround in this PR might be a workable stopgap prior to modularization. @knoblochtobias, did all of osc.js' unit tests pass when you tried them with this change?

Thanks again, both of you. I hugely appreciate the help.

**Comment by colinbdclark** [comment]
Amazing, thanks for confirming @knoblochtobias. It sounds like, then, the best approach might be to merge this workaround in until #119 is completed, and then it might be redundant. I think I've probably maxed out my osc.js time for today, but I'll look into this as soon as I can.

**Pull request merged**
